version: '3.7'

services:
  service-a:
    build:
      context: .
      dockerfile: Dockerfile.a
    ports:
      - "8001:8000"
    depends_on:
      - service-b
      - jaeger
    networks:
      - telemetry

  service-b:
    build:
      context: .
      dockerfile: Dockerfile.b
    ports:
      - "8002:8000"
    networks:
      - telemetry

  jaeger:
    image: jaegertracing/all-in-one:1.31
    ports:
      - "16686:16686"
      - "6831:6831/udp"
    networks:
      - telemetry

networks:
  telemetry:
    driver: bridge
